#!/bin/bash

# this script is created so that the whole compilation can be compressed into
# a unique remote execution of this file

function server_side(){
  cd "$PWD"/server/build;
  cmake -DCMAKE_BUILD_TYPE=Debug ../;
  make;
  mv server ../;
}

function client_side(){
  cd "$PWD"/client/build;
  cmake -DCMAKE_BUILD_TYPE=Debug ../;
  make;
  mv liblclient.so ../;
  mv client ../;
}

function grpc(){
  # assumes that the user uses python virtual environments and more specifically
  # that its name is 'testing'
  # TODO: let the user input either none or its own virtual env name
  source ~/py_envs/testing/bin/activate
  python3 -m grpc_tools.protoc -I. --python_out=../utils/ --grpc_python_out=../utils/ engage.proto;
}

if [ "$1" == "server" ]
then
    server_side;
elif [ "$1" == "client" ]
then
    client_side;
elif [ "$1" == "grpc" ]
then
    grpc;
elif [ "$1" == "all" ]
then
    cd grpc;
    grpc;
    server_side;
    client_side;
else
  echo 'missing or wrong argument'
fi
