#!/bin/bash

function server_side(){

  cd ./server/build;
  cmake ../;
  make;
  mv server ../;
  rm ../log/*;
}

function client_side(){
  cd ./client/build;
  cmake ../;
  make;
  mv client ../;
  rm ../log/*;
}

if [ "$1" == "server" ]
then
    server_side;
elif [ "$1" == "client" ]
then
    client_side;
elif [ "$1" == "both" ]
then
    server_side;
    cd ../../;
    client_side;
else
  echo 'missing or wrong argument'
fi
