#!/bin/bash

function server_side(){

  cmake -DCMAKE_BUILD_TYPE=Debug ../;
  make;
  mv server ../;
  rm ../log/*;
}

function client_side(){
  cmake -DCMAKE_BUILD_TYPE=Debug ../;
  make;
  mv liblclient.so ../;
  mv client ../;
  rm ../log/*;
}

function grpc(){
  source ~/py_envs/testing/bin/activate
  python3 -m grpc_tools.protoc -I. --python_out=../utils/ --grpc_python_out=../utils/ engage.proto;
  echo '[debug] grpc compilation completed'
}

if [ "$1" == "server" ]
then
    server_side;
elif [ "$1" == "client" ]
then
    client_side;
elif [ "$1" == "grpc" ]
then
    grpc;
elif [ "$1" == "all" ]
then
    cd grpc;
    grpc;
    cd ../server/build;
    server_side;
    cd ../../client/build;
    client_side;
else
  echo 'missing or wrong argument'
fi
